package com.wzgiceman.rxretrofitlibrary.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.wzgiceman.rxretrofitlibrary.retrofit_rx.downlaod.DownInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DOWN_INFO".
*/
public class DownInfoDao extends AbstractDao<DownInfo, Long> {

    public static final String TABLENAME = "DOWN_INFO";

    /**
     * Properties of entity DownInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property SavePath = new Property(1, String.class, "savePath", false, "SAVE_PATH");
        public final static Property Url = new Property(2, String.class, "url", false, "URL");
        public final static Property CountLength = new Property(3, long.class, "countLength", false, "COUNT_LENGTH");
        public final static Property ReadLength = new Property(4, long.class, "readLength", false, "READ_LENGTH");
        public final static Property StateInte = new Property(5, int.class, "stateInte", false, "STATE_INTE");
        public final static Property ImageUrl = new Property(6, String.class, "imageUrl", false, "IMAGE_URL");
        public final static Property Title = new Property(7, String.class, "title", false, "TITLE");
        public final static Property Description = new Property(8, String.class, "description", false, "DESCRIPTION");
        public final static Property IsBanner = new Property(9, boolean.class, "isBanner", false, "IS_BANNER");
        public final static Property LiveId = new Property(10, String.class, "liveId", false, "LIVE_ID");
    }


    public DownInfoDao(DaoConfig config) {
        super(config);
    }
    
    public DownInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DOWN_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"SAVE_PATH\" TEXT," + // 1: savePath
                "\"URL\" TEXT," + // 2: url
                "\"COUNT_LENGTH\" INTEGER NOT NULL ," + // 3: countLength
                "\"READ_LENGTH\" INTEGER NOT NULL ," + // 4: readLength
                "\"STATE_INTE\" INTEGER NOT NULL ," + // 5: stateInte
                "\"IMAGE_URL\" TEXT," + // 6: imageUrl
                "\"TITLE\" TEXT," + // 7: title
                "\"DESCRIPTION\" TEXT," + // 8: description
                "\"IS_BANNER\" INTEGER NOT NULL ," + // 9: isBanner
                "\"LIVE_ID\" TEXT);"); // 10: liveId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DOWN_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DownInfo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String savePath = entity.getSavePath();
        if (savePath != null) {
            stmt.bindString(2, savePath);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(3, url);
        }
        stmt.bindLong(4, entity.getCountLength());
        stmt.bindLong(5, entity.getReadLength());
        stmt.bindLong(6, entity.getStateInte());
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(7, imageUrl);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(8, title);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(9, description);
        }
        stmt.bindLong(10, entity.getIsBanner() ? 1L: 0L);
 
        String liveId = entity.getLiveId();
        if (liveId != null) {
            stmt.bindString(11, liveId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DownInfo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String savePath = entity.getSavePath();
        if (savePath != null) {
            stmt.bindString(2, savePath);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(3, url);
        }
        stmt.bindLong(4, entity.getCountLength());
        stmt.bindLong(5, entity.getReadLength());
        stmt.bindLong(6, entity.getStateInte());
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(7, imageUrl);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(8, title);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(9, description);
        }
        stmt.bindLong(10, entity.getIsBanner() ? 1L: 0L);
 
        String liveId = entity.getLiveId();
        if (liveId != null) {
            stmt.bindString(11, liveId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public DownInfo readEntity(Cursor cursor, int offset) {
        DownInfo entity = new DownInfo( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // savePath
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // url
            cursor.getLong(offset + 3), // countLength
            cursor.getLong(offset + 4), // readLength
            cursor.getInt(offset + 5), // stateInte
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // imageUrl
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // title
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // description
            cursor.getShort(offset + 9) != 0, // isBanner
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // liveId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DownInfo entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setSavePath(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCountLength(cursor.getLong(offset + 3));
        entity.setReadLength(cursor.getLong(offset + 4));
        entity.setStateInte(cursor.getInt(offset + 5));
        entity.setImageUrl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTitle(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setDescription(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setIsBanner(cursor.getShort(offset + 9) != 0);
        entity.setLiveId(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DownInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DownInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DownInfo entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
